package com.rvk.mtbs.enums;

public enum City {
	ARIYALUR, CHENGALPATTU, CHENNAI, COIMBATORE, CUDDALORE, DHARMAPURI, DINDIGUL, ERODE, KALLAKURICHI, KANCHIPURAM,
	KANYAKUMARI, KARUR, KRISHNAGIRI, MADURAI, MAYILADUTHURAI, NAGAPATTINAM, NAMAKKAL, NILGIRIS, PERAMBALUR,
	PUDUKKOTTAI, RAMANATHAPURAM, RANIPET, SALEM, SIVAGANGA, TENKASI, THANJAVUR, THENI, THIRUVALLUR, THIRUVARUR,
	THOOTHUKUDI, TIRUCHIRAPPALLI, TIRUNELVELI, TIRUPATTUR, TIRUPPUR, TIRUVANNAMALAI, VELLORE, VILLUPURAM, VIRUDHUNAGAR
}
